name: Publish package to GitHub Packages
on:
  release:
    types: [created]

jobs:
  publish:
    strategy:
      matrix:
        package: [
          'bootstrap-serevr',
          'generate-client-lib',
          'next-auth'
        ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          # Defaults to the user or organization that owns the workflow file
          scope: '@codeyourfaceoff'
          registry-url: 'https://npm.pkg.github.com'
          node-version: '16.x'
      - run: npm ci
      - run: npx nx deploy ${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # build:
  #   runs-on: ubuntu-latest 
  #   permissions: 
  #     contents: read
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v2
  #     # Setup .npmrc file to publish to GitHub Packages
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '16.x'
  #         registry-url: 'https://npm.pkg.github.com'
  #         # Defaults to the user or organization that owns the workflow file
  #         scope: '@octocat'
  #     - run: npm ci
  #     - run: npm build
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}