name: Publish packages to NPM

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    strategy:
      matrix:
        package: [
          'bootstrap-server',
          'generate-client-lib',
          'next-auth'
        ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          # Defaults to the user or organization that owns the workflow file
          scope: '@nest4next'
          node-version: '16.x'
        
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - run: npm ci --cache ~/.npm --prefer-offline
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - run: npx nx deploy ${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
