name: Main

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debug
        env:
          CONTAINS_RC: contains(${{ github.ref }}, '-rc')
        run: echo "CONTAINS: $CONTAINS_RC and GITHUB_REF: $GITHUB_REF"
  
      - name: Release
        uses: softprops/action-gh-release@v1
        run:
          echo contains(${{ github.ref }}, '-rc')
        with:
          body_path: ${{ github.workspace }}/CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: contains(github.ref, '-rc')
